### PR TITLE
Detect hung node-red via regularly polling

### LINKED ISSUE #110: Detect hung Node-RED flows and force restart
The launcher needs to monitor the Node-RED process to check to see if it has hung and is unresponsive. We currently only check that Node-RED starts up and whether the process exits unexpectedly.

A hung process could happen if a user deploys a tight-loop in their flows (eg adding `while(true) {} ` to a function node). Anything that can starve the node.js event loop and prevent the instance from doing anything useful.

The launcher should poll the instance at a suitable interval and if no responses are received for a sustained period, restart the process. The polling interval, timeout interval and retry period all need picking to avoid false-positives, but also provide a timely response.

This should also consider how it plays into the 'restart in safe mode' behaviour - if the instance ends up hanging within seconds each time it starts, then put into safe mode to allow the flows to be edited. Again, need to avoid false-positives here.

Part of https://github.com/flowforge/flowforge/issues/1920

### PR DESCRIPTION
**Pull request by knolleary**
Closes #110 

## Description

This is a follow up to #111 .

It changes the polling done by the launcher to monitor Node-RED.

 - The polling now uses `HTTP HEAD` rather than `GET` to avoid unnecessary network traffic
 - It polls every 10s from the point we start the Node-RED process.
 - If it gets two consecutive errors from the poll, it considers the instance to have hung - and triggers a restart
 - The 'restart loop' logic has been refactored so it can be reused for the hang scenario as well as the existing crash loop handling.

With the current chosen timings, it will take approx 30s to detect and restart a hung Node-RED (two 10s poll intervals to confirm the hang, then 10s timeout waiting for NR to stop before we force kill and restart). We may need to tune these timings - but these values feel an okay starting point that will avoid accidentally killing a Node-RED instance that is temporarily overloaded.

I have tested this with a Function node containing `while(true) {}` that locks up the node.js event loop in two scenarios:

1. allowing NR to start up properly then manually triggering the Function node
    - the hang is detected and Node-RED is restarted
2. triggering the function node automatically on start
    - the hang is detected, NR restarted, it hangs again... after 5 restarts the hang loop is detected and it restarts in safe mode

## Related Issue(s)

#110 

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `flowforge/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `flowforge/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by Steve-Mcl** [comment]
Quick question:

You have deleted the "jitter" part of the code. This was a specific request in a previous task.  Is that not required now?

One for @hardillb 

On the last round of "improving status feedback to platform" (https://github.com/flowforge/flowforge-nr-launcher/pull/65) I remember discussing why we stop polling after "some time". IIRC, it was due to AWS cost? or am I imagining this?

**Comment by hardillb** [comment]
@Steve-Mcl I'm sorry I don't remember that discussion, are you talking about polling from the k8s driver or in the launcher? There would be no cost to making http requests from the launcher to NR

**Comment by Steve-Mcl** [comment]
> @Steve-Mcl I'm sorry I don't remember that discussion, are you talking about polling from the k8s driver or in the launcher? There would be no cost to making http requests from the launcher to NR

Thanks for answering Ben. This is about the launcher making a HTTP call to NR (to check its "alive-ness") so that make this point moot.

Cheers.

File: lib/launcher.js [hunk 1]
```diff
@@ -321,38 +332,97 @@ class Launcher {
...
+                    if (errorCount === 2) {
+                        this.logBuffer.add({ level: 'system', msg: 'Node-RED hang detected.' })
+                        const targetState = this.state
+
+                        // Calling stop will clear the health poll interval
+                        await this.stop()
+                        this.targetState = targetState
+                        // Restart via restartAfterUnexpectedExit as it will check
+                        // for a restart loop
+                        restartAfterUnexpectedExit()
```
Comment (Steve-Mcl) [inline lib/launcher.js:421]: Since `HEALTH_POLL_INTERVAL` is set to 10, this can cause any "heavy" task that takes just above 10s (e.g. a heavy loop math routine or image processing operation) to restart Node-RED.

Scenario: 
1. NR matrix math or image processing task starts 1 second before the next status poll.
2. 1 sec later, `errorCount` is incremented to 1
3. 10 sec later, `errorCount` is incremented to 2 and the process is exited. 

Is this not a bit aggressive?

Comment (knolleary) [reply lib/launcher.js:421]: Indeed. Tuning these parameters needs some careful thought. *Any* value we pick could cause an 'expected' workload to get killed - even if locking up the event loop for long periods is an anti-pattern in node.js world.

We need to balance it against the timeliness of being able to detect a genuine hang. The longer it takes to detect and restart, the longer the flows are down and not working - impacting the availability of the instance. This will become increasingly important as we add HA failover capabilities.

Do you have an alternative set of timings to propose?

With any combination of interval/counts, there will always be a scenario where a workload appears hung to our polling - even if it isn't really. For example, a heavy tasks (that only takes 3s to run), is run every 10 seconds. It happens to align with our polling so to us, every request fails. Even with some random variance in the timing, you could just get unlucky.

File: lib/launcher.js [hunk 2]
```diff
@@ -21,6 +21,12 @@ const MIN_RUNTIME_DEVIATION = 2000 // 2 seconds either side of the mean
 /** How long wait for Node-RED to cleanly stop before killing */
 const NODE_RED_STOP_TIMEOUT = 10000
 
+/** Interval between status polls of Node-RED used to detect a hung runtime */
+const HEALTH_POLL_INTERVAL = 10000
+
+/** Timeout to apply to health polling requests */
+const HEALTH_POLL_TIMEOUT = 100
+
```
Comment (Steve-Mcl) [inline lib/launcher.js:29]:
```suggestion
/** Interval between status polls of Node-RED used to detect a hung runtime */
const HEALTH_POLL_INTERVAL = 7499 // A prime number (to minimise syncing with other processes)

/** Timeout to apply to health polling requests */
const HEALTH_POLL_TIMEOUT = HEALTH_POLL_INTERVAL - 500 // Allow 500ms to avoid overlapping requests

/** The number of consecutive timeouts before considering a NR hang */
const HEALTH_POLL_MAX_ERROR_COUNT = 3

```

As discussed, this works better for responsive ness and avoiding false positives.

NOTE: the new CONST `HEALTH_POLL_MAX_ERROR_COUNT` is used in place of the hard coded number.  Accept this suggestion only if you accept the next suggestion

File: lib/launcher.js [hunk 3]
```diff
@@ -321,38 +332,97 @@ class Launcher {
...
+                statusPoll().then(() => {
+                    // A healthly result
+                    errorCount = 0
+                    if (this.state === States.STARTING) {
+                        this.state = States.RUNNING
+                    }
+                }).catch(async _ => {
+                    // Error polling Node-RED settings page
+                    errorCount++
+                    if (errorCount === 2) {
```
Comment (Steve-Mcl) [inline lib/launcher.js:412]:
```suggestion
                statusPoll().then(() => {
                    // A healthy result
                    errorCount = 0
                    if (this.state === States.STARTING) {
                        this.state = States.RUNNING
                    }
                }).catch(async _ => {
                    // Error polling Node-RED settings page
                    errorCount++
                    if (errorCount === HEALTH_POLL_MAX_ERROR_COUNT) {
```

**Review by Steve-Mcl — CHANGES_REQUESTED** [review]
As discussed, we can achieve a bit better detection by increasing the timeout, reducing the poll rate and increasing the error count.

The below flow was used in testing:


image


```
[{"id":"6318c81ce1d0fb8c","type":"function","z":"08c327c2653de72a","name":"cause extreme load","func":"const sleep = ms => new Promise(r => setTimeout(r, ms));\nconst DURATION = msg.duration ? msg.duration : 20 // 20 sec\nlet cycles = msg.cycles || 1\nconst TOTAL_CYCLES = cycles\nlet sleepTime = msg.sleep || 0\nlet run = true\nlet cycleStartTime = Date.now()\nwhile (run && cycles > 0) {\n    const now = Date.now()\n    if ((now - cycleStartTime) > (DURATION * 1000) ) {\n        if (sleepTime) {\n            await sleep(sleepTime * 1000.0)\n        }\n        cycles--\n        const cs = `was busy for ${DURATION}s, slept for ${sleepTime}s, another ${cycles} cycles to go`\n        console.log(cs)\n        node.send({payload: cs})\n        if (!cycles) {\n            run = false\n            break\n        }\n        cycleStartTime = Date.now()\n    }\n}\nconst s = \"All done. Total time since started: \" + ((Date.now() - cycleStartTime) / 1000).toFixed(2) + \"s\"\nconsole.log(s)\nmsg.payload = s\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":510,"y":680,"wires":[["d2fc8eaa6314b126"]]},{"id":"5da9d1b70fc2f7a9","type":"inject","z":"08c327c2653de72a","name":"thrash 3s, sleep 0.1s, 10 times","props":[{"p":"duration","v":"3","vt":"num"},{"p":"sleep","v":"0.1","vt":"num"},{"p":"cycles","v":"10","vt":"num"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":200,"y":680,"wires":[["6318c81ce1d0fb8c"]]},{"id":"d2fc8eaa6314b126","type":"debug","z":"08c327c2653de72a","name":"debug 173","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":570,"y":740,"wires":[]},{"id":"329a152ba96553fc","type":"inject","z":"08c327c2653de72a","name":"thrash 5s, sleep 5s, 5 times","props":[{"p":"duration","v":"5","vt":"num"},{"p":"sleep","v":"5","vt":"num"},{"p":"cycles","v":"5","vt":"num"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":190,"y":720,"wires":[["6318c81ce1d0fb8c"]]},{"id":"32f9a1ecca7a0268","type":"inject","z":"08c327c2653de72a","name":"thrash 8s, sleep 0.5s, 4 times","props":[{"p":"duration","v":"8","vt":"num"},{"p":"sleep","v":"0.5","vt":"num"},{"p":"cycles","v":"4","vt":"num"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":200,"y":760,"wires":[["6318c81ce1d0fb8c"]]},{"id":"d0fad09356b236ac","type":"inject","z":"08c327c2653de72a","name":"thrash 13s, sleep 0.5s, 4 times","props":[{"p":"duration","v":"13","vt":"num"},{"p":"sleep","v":"0.5","vt":"num"},{"p":"cycles","v":"3","vt":"num"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":200,"y":800,"wires":[["6318c81ce1d0fb8c"]]}]
```

File: lib/launcher.js (hunk 1 above)
Comment (Steve-Mcl) [reply lib/launcher.js:421]: resolving this conversation following bike shedding.

**Comment by knolleary** [comment]
@Steve-Mcl changes accepted - thanks. Review re-requested.
